name: Publish on NPM
on:
  pull_request:
    branches:
      - master
    types: [ closed ]
jobs:
  build:
    # Setup OS and Node Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Latest nodes only
        node-version: [ 14.x ]
    steps:
      # Checkout code
      - name: Checkout Code
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        uses: actions/checkout@v2

      # Make sure we have all branches
      - name: Fetch other branches
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Run Install
      - name: Install environment
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: npm ci

      - name: Run lint
        run: npm run affected:lint -- --base="origin/master"

      - name: Tests coverage
        run: npm run affected:test -- --base="origin/master" --codeCoverage

      - name: Deploy
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          ./.github/scripts/publish-libraries.sh
      - name: Build Docs
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: npm run docs

      - name: Commit files
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Release [skip-ci]" -a || true

      - name: Push changes
        if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_AUTH_TOKEN }}
          tags: true
          force: true
