name: Publish on NPM
on:
  release:
    types: [ published ]
jobs:
  publish:
    # Setup OS and Node Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Latest nodes only
        node-version: [ 14.x ]
    steps:
      # Checkout code
      - name: Checkout Code
        #if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      # Make sure we have all branches
      - name: Fetch other branches
        #if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: git fetch --no-tags --prune --depth=5 origin master

      # Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        #if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      # https://github.com/marketplace/actions/npm-install-cache
      - uses: c-hive/gha-npm-cache@v1
        if: ${{ !env.ACT }}

      # Run Install
      - name: Install environment
        #if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: npm ci

      - name: Run lint
        run: npm run affected:lint -- --base="origin/master"

      - name: Tests coverage
        run: npm run affected:test -- --base="origin/master" --codeCoverage

      - name: Builds components
        run: npm run build --prod --with-deps --base="origin/master"

      - name: Raise version of tagged libraries
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          arrIN=(${LATEST_TAG//_/ })
          LIBRARY=${arrIN[0]}
          VERSION=${arrIN[1]}
          echo $LIBS
          echo $VERSION
          if [ -d "$PWD/packages/$LIBRARY" ]; then
            cd $PWD/packages/$LIBRARY
            npm version ${VERSION}  --allow-same-version
            echo "Bumping $LIBRARY"
            cd ..
            cd ..
          fi

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Commit files
        #if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Release [skip-ci]" -a || true

      - name: Push changes
        #if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_AUTH_TOKEN }}
          tags: true
          force: true

      - name: Deploy

        #if: github.event.pull_request.merged == true && contains(github.event.commits[0].message, '[skip-ci]') == false
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          arrIN=(${LATEST_TAG//_/ })
          LIBRARY=${arrIN[0]}
          VERSION=${arrIN[1]}
          echo "DEPLOY"
          echo $LIBS
          echo $VERSION
          npm config set registry https://registry.npmjs.org/
          if [ -d "$PWD/packages/$LIBRARY" ]; then
            cd $PWD/packages/$LIBRARY
            npm config set scope rbtechdev
            npm publish --access=public
          else
            echo "No library: ${LIBRARY}"
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

