name: Publish on NPM
on:
  release:
    types: [ published ]
jobs:
  publish:
    # Setup OS and Node Version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Latest nodes only
        node-version: [ 16.16 ]
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_AUTH_TOKEN }}


      # Make sure we have all branches
      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin master

      # Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Set variables
        run: |
          LATEST_TAG=${{ github.event.release.tag_name }}
          echo $LATEST_TAG
          arrIN=(${LATEST_TAG//_/ })
          echo "LIBRARY=${arrIN[0]}" >> $GITHUB_ENV
          echo "VERSION=${arrIN[1]}" >> $GITHUB_ENV
          echo $LIBS
          echo $VERSION

      # Run Install

      - name: Install environment
        run: npm ci

      - name: Run lint
        run: npm run affected:lint -- --base="origin/master"

      - name: Tests coverage
        run: npm run affected:test -- --base="origin/master" --codeCoverage

      - name: Setup version of tagged libraries
        run: |
          if [ -d "$PWD/packages/$LIBRARY" ]; then
            cd $PWD/packages/$LIBRARY
            npm version ${VERSION}  --allow-same-version
            echo "Bumping $LIBRARY"
            cd ..
            cd ..
          fi

      - name: Builds components
        run: npm run build --prod --with-deps --base="origin/master"

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Commit updated library package.json version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: chore($LIBRARY)"':'" released $VERSION
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
          commit_author: Author <actions@github.com>
          file_pattern: packages/${LIBRARY}/package.json
          push_options: '--force -a || true'

      - name: Deploy

        run: |
          echo "Publishing on npmjs ${LIBRARY} - version: ${VERSION}"
          if [ -d "$PWD/dist/packages/$LIBRARY" ]; then
            cd $PWD/dist/packages/$LIBRARY
            npm publish --access=public --ignore-scripts
          else
            echo "No library: ${LIBRARY}"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

